services:
  postgres:
    image: postgres:16-alpine
    container_name: project-s7-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_s7
    ports:
      - "5432:5432"
    volumes:
      - project_s7_pg:/var/lib/postgresql/data

volumes:
  project_s7_pg:
