# Use this if you set Railway root directory to `backend`
[phases.setup]
nixPkgs = ["openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "npm run start:prod"
